<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE menus [
    <!ELEMENT menus (menu*)>

    <!ELEMENT menu ANY>
    <!ATTLIST menu
        id  ID  #IMPLIED
    >

    <!ELEMENT item ANY>
    <!ATTLIST item
        href    CDATA   #REQUIRED
    >
]>

<menus>
    <menu id="default">
        <item href="#home"><![CDATA[<i>Home</i>]]></item>
        <item href="#links">My links</item>
        <item href="#stuff">My stuff</item>
    </menu>
</menus>
